Repository YimMenu/YimMenu, pull requests merged in 2022-05, with the labels that each got.

#116 feat(Self): Add local visibility option
  BigBaseV2/src/backend/looped/self/invisibility.cpp
  BigBaseV2/src/backend/looped/session/local_time.cpp
  BigBaseV2/src/core/globals.hpp
  BigBaseV2/src/views/view_self.cpp
Labels: enhancement

#118 feat(GUI): Simplifying the gui
  BigBaseV2/backend/looped/rgb/synced_fade.cpp
  BigBaseV2/backend/looped/rgb/synced_spam.cpp
  BigBaseV2/drive_on_water.cpp
  BigBaseV2/rgb_paint.cpp
  BigBaseV2/src/backend/looped/self/super_run.cpp
  BigBaseV2/src/core/globals.hpp
  BigBaseV2/src/gui.cpp
  BigBaseV2/src/gui/components/components.hpp
  BigBaseV2/src/gui/components/nav_button.cpp
  BigBaseV2/src/gui/components/nav_item.cpp
  BigBaseV2/src/gui/handling/handling_current_profile.cpp
  BigBaseV2/src/gui/handling/handling_my_profiles.cpp
  BigBaseV2/src/gui/handling/handling_saved_profiles.cpp
  BigBaseV2/src/gui/handling/handling_search.cpp
  BigBaseV2/src/gui/handling/modals/update_handling.cpp
  BigBaseV2/src/main.cpp
  BigBaseV2/src/services/gui_service.cpp
  BigBaseV2/src/services/gui_service.hpp
  BigBaseV2/src/util/mobile.hpp
  BigBaseV2/src/views/core/view_active_view.cpp
  BigBaseV2/src/views/core/view_heading.cpp
  BigBaseV2/src/views/core/view_navigation.cpp
  BigBaseV2/src/views/core/view_notifications.cpp
  BigBaseV2/src/views/core/view_root.cpp
  BigBaseV2/src/views/network/view_session.cpp
  BigBaseV2/src/views/network/view_spoofing.cpp
  BigBaseV2/src/views/players/view_player.cpp
  BigBaseV2/src/views/players/view_players.cpp
  BigBaseV2/src/views/self/view_mobile.cpp
  BigBaseV2/src/views/self/view_self.cpp
  BigBaseV2/src/views/self/view_teleport.cpp
  BigBaseV2/src/views/self/view_weapons.cpp
  BigBaseV2/src/views/settings/view_debug.cpp
  BigBaseV2/src/views/settings/view_esp_settings.cpp
  BigBaseV2/src/views/settings/view_gui_settings.cpp
  BigBaseV2/src/views/settings/view_notification_settings.cpp
  BigBaseV2/src/views/settings/view_protection_settings.cpp
  BigBaseV2/src/views/settings/view_settings.cpp
  BigBaseV2/src/views/vehicle/view_spawn.cpp
  BigBaseV2/src/views/vehicle/view_vehicle.cpp
  BigBaseV2/src/views/view.hpp
  BigBaseV2/src/views/view_active_view.cpp
  BigBaseV2/src/views/view_debug.cpp
  BigBaseV2/src/views/view_mobile.cpp
  BigBaseV2/src/views/view_navigation.cpp
  BigBaseV2/src/views/view_notifications.cpp
  BigBaseV2/src/views/view_self.cpp
  BigBaseV2/src/views/view_session.cpp
  BigBaseV2/src/views/view_settings.cpp
  BigBaseV2/src/views/view_spoofing.cpp
  BigBaseV2/src/views/view_vehicle.cpp
  BigBaseV2/src/views/view_weapons.cpp
Labels: enhancement, gui

#163 Fix Script Event Handler hook from clogging event queue
  BigBaseV2/src/function_types.hpp
  BigBaseV2/src/hooking.cpp
  BigBaseV2/src/hooking.hpp
  BigBaseV2/src/hooks/received_event.cpp
  BigBaseV2/src/hooks/script_event_handler.cpp
  BigBaseV2/src/pointers.cpp
  BigBaseV2/src/pointers.hpp
Labels: fix
